### ISSUE TITLE
sample.key indexed by column number instead of name

### ISSUE THREAD

**Issue by lhmelo** [IngallsLabUW/B-MIS-normalization#2]
TQS script only(commit 4ae3fbf): Line 109, the full join is indexed by column number instead of column name.  The numbers didn’t quite line up for me, so I converted the indices from numbers to names.

**Comment by kheal** [comment]
I don't see where you're talking about - line 109 on that commit is 
"+  mutate(Replicate.Name = Replicate.Name %>%"
I think maybe you mean line 119?  I made that one call up by name instead of index
