### ISSUE TITLE
summarize/summarise

### ISSUE THREAD

**Issue by lhmelo** [IngallsLabUW/B-MIS-normalization#3]
"summarize" is used instead of "summarise" throughout the BMIS code- I needed to convert all "summarize" to "summarise" in order to execute the code. I'm not sure if this is due to some strange configuration in my version of R, but it might be worth checking with a few users to see what works most consistantly.

**Comment by kheal** [comment]
Known issue with summarize vs summarise.  Some versions use one, some use the other.  I changed it to summarise throughout.
